[package]
name = "astretch"
version = "0.1.0"
edition = "2024"
tags = ["audio", "time-stretching", "pitch-shifting", "signal-smith", "signalsmith", "phase-vocoder", "rustfft"]

[dependencies]
num = "0.4.3"
rand = "0.9.2"
rustfft = "6.4.1"
wide = "1.1.1"
realfft = "3.5.0"
